---
# pre-commit is a tool to perform a predefined set of tasks manually and/or
# automatically before git commits are made.
#
# Config reference: https://pre-commit.com/#pre-commit-configyaml---top-level
#
# Common tasks
#
# - Run on all files:   pre-commit run --all-files
# - Register git hooks: pre-commit install --install-hooks
#
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # Autoupdate: Python code
  - repo: https://github.com/asottile/pyupgrade
    rev: 75992aaa40730136014f34227e0135f63fc951b4 # frozen: v3.21.2
    hooks:
      - id: pyupgrade
        args: [--py312-plus]

  # Automatically sort python imports
  - repo: https://github.com/PyCQA/isort
    rev: 0a09c783808cfe77bb3269250f663ff733d23302 # frozen: 7.0.0
    hooks:
      - id: isort
        args: [--profile, black]

  # Autoformat: Python code
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 831207fd435b47aeffdf6af853097e64322b4d44  # frozen: 25.12.0
    hooks:
      - id: black
        args: [--target-version=py312]

  # Check python code static typing
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: a66e98df7b4aeeb3724184b332785976d062b92e  # frozen: v1.19.1
    hooks:
      - id: mypy
        args: [--config, ./mypy.ini]
        additional_dependencies:
          [
            "numpy",
            "pytest",
            "requests",
            "urllib3",
            "types-requests",
            "types-tabulate",
            "types-urllib3",
          ]
        # Unfortunately, `pre-commit` only runs on modified files
        # This doesn't work well with `mypy --follow-imports error`
        # See: https://github.com/pre-commit/mirrors-mypy/issues/34#issuecomment-1062160321
        #
        # To work around this we run `mypy` only in manual mode
        # So it won't run as part of `git commit` command,
        # but it will still be run as part of `pre-commit` workflow and give expected results
        stages: [manual]

  # Autoformat: YAML, JSON, Markdown, etc.
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: 14abee445aea04b39069c19b4bd54efff6775819  # frozen: v3.7.4
    hooks:
      - id: prettier
        exclude: "{{cookiecutter.stack_name}}/.github/workflows/docker.yml"

  # `pre-commit sample-config` default hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  # Lint: Dockerfile
  - repo: https://github.com/hadolint/hadolint
    rev: 4e697ba704fd23b2409b947a319c19c3ee54d24f # frozen: v2.14.0
    hooks:
      - id: hadolint-docker
        entry: hadolint/hadolint:v2.14.0 hadolint

  # Lint: YAML
  - repo: https://github.com/adrienverge/yamllint
    rev: 79a6b2b1392eaf49cdd32ac4f14be1a809bbd8f7 # frozen: v1.37.1
    hooks:
      - id: yamllint
        args: ["-d {extends: relaxed, rules: {line-length: disable}}", "-s"]
        exclude: "{{cookiecutter.stack_name}}/.github/workflows/docker.yml"

  # Lint: Python
  - repo: https://github.com/PyCQA/flake8
    rev: d93590f5be797aabb60e3b09f2f52dddb02f349f # frozen: 7.3.0
    hooks:
      - id: flake8

  # Lint: Markdown
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: 7339935a3036f096ee0d7f1f047a9ec41707d4c1  # frozen: v0.20.0
    hooks:
      - id: markdownlint-cli2
        args: [--fix]

# pre-commit.ci config reference: https://pre-commit.ci/#configuration
ci:
  autoupdate_schedule: monthly
  # Docker hooks do not work in pre-commit.ci
  # See: <https://github.com/pre-commit-ci/issues/issues/11>
  skip: [hadolint-docker]
